version: '3'

services:
  db:
    image: postgres
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - '5432:5432'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # volumes: 
    #   - db:/var/lib/postgresql/data

  api:

    build: ./backend

    container_name: backend

    command: poetry run ./run.sh 

    # network_mode: "host"
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8001:8001"

  frontend:

    build: ./frontend

    container_name: frontend

    command: npm run serve

    depends_on:
      - api

    ports:
      - "8080:8080"


# volumes:
#   db:
#     driver: local